### ISSUE TITLE
Баг фикс: Не добавляется новый предмет в форме добавления учителя

### ISSUE THREAD

**Issue by xx3u** [xx3u/amal_frontend#158]
**Описание бага**
В чем баг.

**Шаги воспроизведения:**

**Наблюдаемое поведение:**
Описание что произошло

**Ожидаемое поведение:**
Описание того, что должно было произойти.

**Причины:**
Нужно проверить причину https://github.com/xx3u/amal_backend/issues/79

**Вариант решения:**
Что необходимо сделать.

**Comment by OmegonAlpharius** [comment]
Исправлен на  xx3u/amal_backend#79
